FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.RHI" = "*", "Sedulous.RenderGraph" = "*", "Sedulous.Geometry" = "*", "Sedulous.Shaders" = "*", "Sedulous.Materials" = "*", "Sedulous.Models" = "*", "Sedulous.Imaging" = "*", "Sedulous.Engine.Animation" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.Renderer"
TargetType = "BeefLib"
