FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Editor.Core" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Animation" = "*", "Sedulous.GUI" = "*"}

[Project]
Name = "Sedulous.Editor.Animation"
TargetType = "BeefLib"
