FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Jobs" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "Sedulous.Engine.App"
StartupObject = "Sedulous.Engine.App.Program"
