FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.Engine.Animation" = "*", "Sedulous.Foundation.Mathematics.Serialization" = "*"}

[Project]
Name = "Sedulous.Geometry"
TargetType = "BeefLib"
StartupObject = "Sedulous.Geometry.Program"
