FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Models" = "*", "ufbx-Beef" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Imaging" = "*"}

[Project]
Name = "Sedulous.Models.FBX"
TargetType = "BeefLib"
StartupObject = "Sedulous.Models.FBX.Program"
