FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", "Sedulous.Foundation" = "*"}

[Project]
Name = "Sedulous.Foundation.Mathematics"
TargetType = "BeefLib"
StartupObject = "Sedulous.Foundation.Mathematics.Program"
