FileVersion = 1

[Project]
Name = "ufbx-Beef"
TargetType = "BeefLib"
StartupObject = "ufbx_Beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/ufbx.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/ufbx.lib"]
