FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Foundation.Logging" = "*"}

[Project]
Name = "Sedulous.RHI"
TargetType = "BeefLib"
