FileVersion = 1

[Project]
Name = "Sedulous.Foundation.Mathematics.Serialization"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Serialization" = "*"
"Sedulous.Foundation.Mathematics" = "*"
