FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Foundation" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shaders" = "*", "Sedulous.Foundation.Logging" = "*"}

[Project]
Name = "SampleFramework"
