FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Jobs" = "*", "Sedulous.OpenDDL" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*", "Sedulous.Serialization.OpenDDL" = "*", corlib = "*", "Sedulous.Foundation.Mathematics" = "*"}

[Project]
Name = "Sedulous.Resources.Tests"
TargetType = "BeefTest"
