FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Imaging" = "*", "Sedulous.Fonts" = "*", "stb_truetype-Beef" = "*"}

[Project]
Name = "Sedulous.Fonts.TTF"
TargetType = "BeefLib"
