FileVersion = 1
Dependencies = {corlib = "*", SampleFramework = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*"}

[Project]
Name = "RHIBlending"
StartupObject = "RHIBlending.Program"
