namespace Sedulous.RHI;

using System;

/// The type of GPU query.
enum QueryType
{
	/// Occlusion query - counts how many samples pass depth/stencil tests.
	/// Results are uint64 values representing the number of samples that passed.
	Occlusion,

	/// Timestamp query - records the GPU timestamp at a specific point.
	/// Results are uint64 values representing GPU ticks.
	/// Use IQueue.GetTimestampPeriod() to convert to nanoseconds.
	Timestamp,

	/// Pipeline statistics query - gathers various pipeline statistics.
	/// Results are PipelineStatistics structures.
	PipelineStatistics
}

/// Pipeline statistics that can be queried.
[CRepr]
struct PipelineStatistics
{
	/// Number of vertices processed by the input assembler.
	public uint64 InputAssemblyVertices;

	/// Number of primitives processed by the input assembler.
	public uint64 InputAssemblyPrimitives;

	/// Number of vertex shader invocations.
	public uint64 VertexShaderInvocations;

	/// Number of geometry shader invocations.
	public uint64 GeometryShaderInvocations;

	/// Number of primitives generated by the geometry shader.
	public uint64 GeometryShaderPrimitives;

	/// Number of primitives sent to the rasterizer.
	public uint64 ClippingInvocations;

	/// Number of primitives output by the rasterizer.
	public uint64 ClippingPrimitives;

	/// Number of fragment shader invocations.
	public uint64 FragmentShaderInvocations;

	/// Number of tessellation control shader patches.
	public uint64 TessellationControlShaderPatches;

	/// Number of tessellation evaluation shader invocations.
	public uint64 TessellationEvaluationShaderInvocations;

	/// Number of compute shader invocations.
	public uint64 ComputeShaderInvocations;
}
