FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", SampleFramework = "*"}

[Project]
Name = "RHITexturedQuad"
StartupObject = "RHITexturedQuad.Program"
