FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Engine.Animation" = "*", "Sedulous.Engine.Navigation" = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Jobs" = "*", "Sedulous.Resources" = "*", "Sedulous.Materials" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Imaging" = "*", "Sedulous.Imaging.STB" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*", "Sedulous.Models.FBX" = "*", "Sedulous.Textures" = "*", "Sedulous.Imaging.SDL" = "*", "Sedulous.Profiler" = "*"}

[Project]
Name = "Sedulous.Engine.App"
StartupObject = "Sedulous.Engine.App.Program"
