FileVersion = 1
Dependencies = {corlib = "*", SampleFramework = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Foundation" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*"}

[Project]
Name = "RHIDepthBuffer"
StartupObject = "RHIDepthBuffer.Program"
